spring:
    profiles:
        active: dev

    datasource:
        url: jdbc:mysql://mysql:3306/db_documentos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
        username: aduana
        password: aduana123
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
    application:
      name: documentos

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false