server:
  port: 8083

spring:
  application:
    name: historial
  datasource:
    url: jdbc:mysql://localhost:3306/db_historial?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: aduana
    password: aduana123
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true