spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        #alertas
        - id: alertas-service
          uri: lb://alertas
          predicates:
            - Path=/api/alertas/**
          filters:
            - RewritePath=/api/alertas/(?<segment>.*), /api/v1/alertas/${segment}

        #documentos
        - id: documentos-service
          uri: lb://documentos
          predicates:
            - Path=/api/documentos/**
          filters:
            - StripPrefix=1

        #exportaciones
        - id: exportaciones-service
          uri: lb://exportaciones
          predicates:
            - Path=/api/exportaciones/**
          filters:
            - RewritePath=/api/exportaciones/(?<segment>.*), /api/v1/exportaciones/${segment}

        #historial
        - id: historial-service
          uri: lb://historial
          predicates:
            - Path=/api/historial/**
          filters:
            - RewritePath=/api/historial/(?<segment>.*), /api/v1/historiales/${segment}

        #importaciones
        - id: importaciones-service
          uri: lb://importaciones
          predicates:
            - Path=/api/importaciones/**
          filters:
            - RewritePath=/api/importaciones/(?<segment>.*), /api/v1/importaciones/${segment}

        #impuestos
        - id: impuetos-service
          uri: lb://impuestos
          predicates:
            - Path=/api/impuestos/**
          filters:
            - RewritePath=/api/impuestos/(?<segment>.*), /api/v1/impuestos/${segment}

        #mercancia
        - id: mercancia-service
          uri: lb://mercancias
          predicates:
            - Path=/api/mercancias/**
          filters:
            - StripPrefix=1

        #paises
        - id: paises-service
          uri: lb://paises
          predicates:
            - Path=/api/paises/**
          filters:
            - StripPrefix=1

        #reportes
        - id: reportes-service
          uri: lb://reportes
          predicates:
            - Path=/api/reportes/**
          filters:
            - StripPrefix=1

        #usuarios
        - id: usuarios-service
          uri: lb://usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - RewritePath=/api/usuarios/(?<segment>.*), /api/v1/usuarios/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8080